export const CUTE_QUOTES = [
  {
    id: "cute-010",
    text: "I'm not afraid of storms, for I'm learning how to sail my ship.",
    author: "Louisa May Alcott",
    source: "Little Women",
    sourceUrl: "https://www.gutenberg.org/ebooks/514",
    placement: "program_overview_before_starting",
    tone: "reassuring",
    publicDomain: true,
  },
  {
    id: "cute-012",
    text: "If you look the right way, you can see that the whole world is a garden.",
    author: "Frances Hodgson Burnett",
    source: "The Secret Garden",
    sourceUrl: "https://www.gutenberg.org/ebooks/17396",
    placement: "program_overview_before_starting",
    tone: "optimistic",
    publicDomain: true,
  },
  {
    id: "cute-013",
    text: "Tomorrow is always fresh, with no mistakes in it yet.",
    author: "L. M. Montgomery",
    source: "Anne of Green Gables",
    sourceUrl: "https://www.gutenberg.org/ebooks/45",
    placement: "program_overview_before_starting",
    tone: "optimistic",
    publicDomain: true,
  },
  {
    id: "cute-015",
    text: "I am no bird; and no net ensnares me: I am a free human being with an independent will.",
    author: "Charlotte Bront\u00eb",
    source: "Jane Eyre",
    sourceUrl: "https://www.gutenberg.org/ebooks/1260",
    placement: "program_overview_before_starting",
    tone: "defiant",
    publicDomain: true,
  },
  {
    id: "cute-016",
    text: "Nothing contributes so much to tranquilize the mind as a steady purpose.",
    author: "Mary Shelley",
    source: "Frankenstein",
    sourceUrl: "https://www.gutenberg.org/ebooks/84",
    placement: "program_overview_before_starting",
    tone: "reflective",
    publicDomain: true,
  },
  {
    id: "cute-017",
    text: "That brain of mine is something more than merely mortal; as time will show.",
    author: "Ada Lovelace",
    source: "Letter to Charles Babbage, 1844",
    placement: "program_overview_before_starting",
    tone: "confident",
    publicDomain: true,
  },
  {
    id: "cute-021",
    text: "There is a stubbornness about me that never can bear to be frightened at the will of others.",
    author: "Jane Austen",
    source: "Pride and Prejudice",
    sourceUrl: "https://www.gutenberg.org/ebooks/1342",
    placement: "program_overview_before_starting",
    tone: "confident",
    publicDomain: true,
  },
  {
    id: "cute-022",
    text: "I try all things; I achieve what I can.",
    author: "Herman Melville",
    source: "Moby-Dick",
    sourceUrl: "https://www.gutenberg.org/ebooks/2701",
    placement: "program_overview_before_starting",
    tone: "grounded",
    publicDomain: true,
  },
  {
    id: "cute-025",
    text: "Wait and hope.",
    author: "Alexandre Dumas",
    source: "The Count of Monte Cristo",
    sourceUrl: "https://www.gutenberg.org/ebooks/1184",
    placement: "program_overview_before_starting",
    tone: "reassuring",
    publicDomain: true,
  },
  {
    id: "cute-026",
    text: "It is never too late to be wise.",
    author: "Daniel Defoe",
    source: "Robinson Crusoe",
    sourceUrl: "https://www.gutenberg.org/ebooks/521",
    placement: "program_overview_before_starting",
    tone: "reassuring",
    publicDomain: true,
  },
  {
    id: "cute-028",
    text: "Whether I shall turn out to be the hero of my own life, or whether that station will be held by anybody else, these pages must show.",
    author: "Charles Dickens",
    source: "David Copperfield",
    sourceUrl: "https://www.gutenberg.org/ebooks/766",
    placement: "program_overview_before_starting",
    tone: "reflective",
    publicDomain: true,
  },
  {
    id: "cute-034",
    text: "Action is eloquence.",
    author: "William Shakespeare",
    source: "Coriolanus",
    sourceUrl: "https://www.gutenberg.org/ebooks/100",
    placement: "workout_general",
    tone: "decisive",
    publicDomain: true,
  },
  {
    id: "cute-035",
    text: "Once more unto the breach, dear friends, once more.",
    author: "William Shakespeare",
    source: "Henry V",
    sourceUrl: "https://www.gutenberg.org/ebooks/100",
    placement: "workout_general",
    tone: "motivational",
    publicDomain: true,
  },
  {
    id: "cute-036",
    text: "The game's afoot: Follow your spirit.",
    author: "William Shakespeare",
    source: "Henry V",
    sourceUrl: "https://www.gutenberg.org/ebooks/100",
    placement: "workout_general",
    tone: "playful",
    publicDomain: true,
  },
  {
    id: "cute-037",
    text: "Suit the action to the word, the word to the action.",
    author: "William Shakespeare",
    source: "Hamlet",
    sourceUrl: "https://www.gutenberg.org/ebooks/100",
    placement: "workout_general",
    tone: "focused",
    publicDomain: true,
  },
  {
    id: "cute-038",
    text: "Strong reasons make strong actions.",
    author: "William Shakespeare",
    source: "King John",
    sourceUrl: "https://www.gutenberg.org/ebooks/100",
    placement: "workout_general",
    tone: "focused",
    publicDomain: true,
  },
  {
    id: "cute-042",
    text: "Experience is merely the name men gave to their mistakes.",
    author: "Oscar Wilde",
    source: "The Picture of Dorian Gray",
    sourceUrl: "https://www.gutenberg.org/ebooks/174",
    placement: "workout_general",
    tone: "witty",
    publicDomain: true,
  },
  {
    id: "cute-043",
    text: "Begin at the beginning, and go on till you come to the end: then stop.",
    author: "Lewis Carroll",
    source: "Alice's Adventures in Wonderland",
    sourceUrl: "https://www.gutenberg.org/ebooks/11",
    placement: "workout_general",
    tone: "structured",
    publicDomain: true,
  },
  {
    id: "cute-053",
    text: "It has long been an axiom of mine that the little things are infinitely the most important.",
    author: "Arthur Conan Doyle",
    source: "The Adventures of Sherlock Holmes",
    sourceUrl: "https://www.gutenberg.org/ebooks/1661",
    placement: "workout_general",
    tone: "focused",
    publicDomain: true,
  },
  {
    id: "cute-055",
    text: "I exist as I am, that is enough.",
    author: "Walt Whitman",
    source: "Leaves of Grass",
    sourceUrl: "https://www.gutenberg.org/ebooks/1322",
    placement: "workout_general",
    tone: "confident",
    publicDomain: true,
  },
  {
    id: "cute-056",
    text: "Forever is composed of nows.",
    author: "Emily Dickinson",
    source: "Poems",
    sourceUrl: "https://www.gutenberg.org/ebooks/12242",
    placement: "workout_general",
    tone: "present",
    publicDomain: true,
  },
  {
    id: "cute-057",
    text: "I like good strong words that mean something.",
    author: "Louisa May Alcott",
    source: "Little Women",
    sourceUrl: "https://www.gutenberg.org/ebooks/514",
    placement: "workout_general",
    tone: "playful",
    publicDomain: true,
  },
  {
    id: "cute-058",
    text: "I know not all that may be coming, but be it what it will, I'll go to it laughing.",
    author: "Herman Melville",
    source: "Moby-Dick",
    sourceUrl: "https://www.gutenberg.org/ebooks/2701",
    placement: "workout_general",
    tone: "resilient",
    publicDomain: true,
  },
  {
    id: "cute-060",
    text: "Procrastination is the thief of time. Collar him.",
    author: "Charles Dickens",
    source: "David Copperfield",
    sourceUrl: "https://www.gutenberg.org/ebooks/766",
    placement: "workout_general",
    tone: "playful",
    publicDomain: true,
  },
  {
    id: "cute-068",
    text: "Angels can fly because they can take themselves lightly.",
    author: "G. K. Chesterton",
    source: "Orthodoxy",
    sourceUrl: "https://www.gutenberg.org/ebooks/130",
    placement: "workout_general",
    tone: "playful",
    publicDomain: true,
  },
  {
    id: "cute-070",
    text: "Life is worth living as long as there's a laugh in it.",
    author: "L. M. Montgomery",
    source: "Anne of Avonlea",
    sourceUrl: "https://www.gutenberg.org/ebooks/47",
    placement: "workout_general",
    tone: "optimistic",
    publicDomain: true,
  },
  {
    id: "cute-080",
    text: "We know what we are, but know not what we may be.",
    author: "William Shakespeare",
    source: "Hamlet",
    sourceUrl: "https://www.gutenberg.org/ebooks/100",
    placement: "workout_strength_hypertrophy",
    tone: "reflective",
    publicDomain: true,
  },
  {
    id: "cute-081",
    text: "Come what come may, time and the hour runs through the roughest day.",
    author: "William Shakespeare",
    source: "Macbeth",
    sourceUrl: "https://www.gutenberg.org/ebooks/100",
    placement: "workout_strength_hypertrophy",
    tone: "resilient",
    publicDomain: true,
  },
  {
    id: "cute-082",
    text: "Bear up, my heart; thou hast borne worse than this.",
    author: "Homer",
    source: "The Odyssey, Samuel Butler translation",
    sourceUrl: "https://www.gutenberg.org/ebooks/1727",
    placement: "workout_strength_hypertrophy",
    tone: "resilient",
    publicDomain: true,
  },
  {
    id: "cute-087",
    text: "Long is the way and hard, that out of Hell leads up to light.",
    author: "John Milton",
    source: "Paradise Lost",
    sourceUrl: "https://www.gutenberg.org/ebooks/26",
    placement: "workout_strength_hypertrophy",
    tone: "serious",
    publicDomain: true,
  },
  {
    id: "cute-089",
    text: "We never know how high we are till we are called to rise.",
    author: "Emily Dickinson",
    source: "Poems",
    sourceUrl: "https://www.gutenberg.org/ebooks/12242",
    placement: "workout_strength_hypertrophy",
    tone: "motivational",
    publicDomain: true,
  },
  {
    id: "cute-090",
    text: "I am larger, better than I thought; I did not know I held so much goodness.",
    author: "Walt Whitman",
    source: "Leaves of Grass",
    sourceUrl: "https://www.gutenberg.org/ebooks/1322",
    placement: "workout_strength_hypertrophy",
    tone: "confident",
    publicDomain: true,
  },
  {
    id: "cute-099",
    text: "We learn from failure, not from success!",
    author: "Bram Stoker",
    source: "Dracula",
    sourceUrl: "https://www.gutenberg.org/ebooks/345",
    placement: "workout_strength_hypertrophy",
    tone: "resilient",
    publicDomain: true,
  },
  {
    id: "cute-101",
    text: "Beware, for I am fearless and therefore powerful.",
    author: "Mary Shelley",
    source: "Frankenstein",
    sourceUrl: "https://www.gutenberg.org/ebooks/84",
    placement: "workout_strength_hypertrophy",
    tone: "defiant",
    publicDomain: true,
  },
  {
    id: "cute-103",
    text: "My strength is as the strength of ten, because my heart is pure.",
    author: "Alfred, Lord Tennyson",
    source: "Sir Galahad",
    sourceUrl: "https://www.gutenberg.org/ebooks/8601",
    placement: "workout_strength_hypertrophy",
    tone: "confident",
    publicDomain: true,
  },
  {
    id: "cute-105",
    text: "To strive, to seek, to find, and not to yield.",
    author: "Alfred, Lord Tennyson",
    source: "Ulysses",
    sourceUrl: "https://www.gutenberg.org/ebooks/8601",
    placement: "workout_strength_hypertrophy",
    tone: "motivational",
    publicDomain: true,
  },
  {
    id: "cute-110",
    text: "Our bodies are our gardens, to the which our wills are gardeners.",
    author: "William Shakespeare",
    source: "Othello",
    sourceUrl: "https://www.gutenberg.org/ebooks/100",
    placement: "workout_cardio_health",
    tone: "grounded",
    publicDomain: true,
  },
  {
    id: "cute-111",
    text: "There is nothing\u2014absolutely nothing\u2014half so much worth doing as simply messing about in boats.",
    author: "Kenneth Grahame",
    source: "The Wind in the Willows",
    sourceUrl: "https://www.gutenberg.org/ebooks/289",
    placement: "workout_cardio_health",
    tone: "playful",
    publicDomain: true,
  },
  {
    id: "cute-112",
    text: "I travel not to go anywhere, but to go. I travel for travel's sake.",
    author: "Robert Louis Stevenson",
    source: "Travels with a Donkey in the C\u00e9vennes",
    sourceUrl: "https://www.gutenberg.org/ebooks/535",
    placement: "workout_cardio_health",
    tone: "adventurous",
    publicDomain: true,
  },
  {
    id: "cute-118",
    text: "It's been my experience that you can nearly always enjoy things if you make up your mind firmly that you will.",
    author: "L. M. Montgomery",
    source: "Anne of Green Gables",
    sourceUrl: "https://www.gutenberg.org/ebooks/45",
    placement: "workout_cardio_health",
    tone: "optimistic",
    publicDomain: true,
  },
  {
    id: "cute-119",
    text: "Where you tend a rose, my lad, a thistle cannot grow.",
    author: "Frances Hodgson Burnett",
    source: "The Secret Garden",
    sourceUrl: "https://www.gutenberg.org/ebooks/17396",
    placement: "workout_cardio_health",
    tone: "grounded",
    publicDomain: true,
  },
  {
    id: "cute-121",
    text: "We should go forth on the shortest walk, perchance, in the spirit of undying adventure.",
    author: "Henry David Thoreau",
    source: "Walking",
    sourceUrl: "https://en.wikisource.org/wiki/Walking_(Thoreau)",
    placement: "workout_cardio_health",
    tone: "adventurous",
    publicDomain: true,
  },
  {
    id: "cute-122",
    text: "Every time I see an adult on a bicycle, I no longer despair for the future of the human race.",
    author: "H. G. Wells",
    source: "The Wheels of Chance",
    sourceUrl: "https://www.gutenberg.org/ebooks/1264",
    placement: "workout_cardio_health",
    tone: "playful",
    publicDomain: true,
  },
  {
    id: "cute-123",
    text: "Health is not only to be well, but to use well every power we have.",
    author: "Florence Nightingale",
    source: "Health-nursing essay, 1893",
    placement: "workout_cardio_health",
    tone: "grounded",
    publicDomain: true,
  },
  {
    id: "cute-124",
    text: "In every walk with Nature one receives far more than he seeks.",
    author: "John Muir",
    source: "Selected writings",
    sourceUrl: "https://vault.sierraclub.org/john_muir_exhibit/writings/",
    placement: "workout_cardio_health",
    tone: "restorative",
    publicDomain: true,
  },
  {
    id: "cute-127",
    text: "The first wealth is health.",
    author: "Ralph Waldo Emerson",
    source: "The Conduct of Life",
    sourceUrl: "https://www.gutenberg.org/ebooks/39827",
    placement: "workout_cardio_health",
    tone: "grounded",
    publicDomain: true,
  },
  {
    id: "cute-128",
    text: "It takes all the running you can do, to keep in the same place.",
    author: "Lewis Carroll",
    source: "Through the Looking-Glass",
    sourceUrl: "https://www.gutenberg.org/ebooks/12",
    placement: "workout_cardio_health",
    tone: "playful",
    publicDomain: true,
  },
  {
    id: "cute-133",
    text: "No legacy is so rich as honesty.",
    author: "William Shakespeare",
    source: "All's Well That Ends Well",
    sourceUrl: "https://www.gutenberg.org/ebooks/100",
    placement: "review_on_track",
    tone: "reflective",
    publicDomain: true,
  },
  {
    id: "cute-135",
    text: "Diligence is the mother of good fortune.",
    author: "Miguel de Cervantes",
    source: "Don Quixote, John Ormsby translation",
    sourceUrl: "https://www.gutenberg.org/ebooks/996",
    placement: "review_on_track",
    tone: "affirming",
    publicDomain: true,
  },
  {
    id: "cute-136",
    text: "I have been bent and broken, but\u2014I hope\u2014into a better shape.",
    author: "Charles Dickens",
    source: "Great Expectations",
    sourceUrl: "https://www.gutenberg.org/ebooks/1400",
    placement: "review_on_track",
    tone: "resilient",
    publicDomain: true,
  },
  {
    id: "cute-139",
    text: "The years teach much which the days never know.",
    author: "Ralph Waldo Emerson",
    source: "Essays, First Series",
    sourceUrl: "https://www.gutenberg.org/ebooks/16643",
    placement: "review_on_track",
    tone: "reflective",
    publicDomain: true,
  },
  {
    id: "cute-144",
    text: "The more I study, the more insatiable do I feel my genius for it to be.",
    author: "Ada Lovelace",
    source: "Letter, 1841",
    placement: "review_on_track",
    tone: "motivational",
    publicDomain: true,
  },
  {
    id: "cute-149",
    text: "Hope is the thing with feathers that perches in the soul.",
    author: "Emily Dickinson",
    source: "Poems",
    sourceUrl: "https://www.gutenberg.org/ebooks/12242",
    placement: "review_on_track",
    tone: "hopeful",
    publicDomain: true,
  },
  {
    id: "cute-150",
    text: "It's not what the world holds for you. It's what you bring to it.",
    author: "L. M. Montgomery",
    source: "Anne of Avonlea",
    sourceUrl: "https://www.gutenberg.org/ebooks/47",
    placement: "review_on_track",
    tone: "affirming",
    publicDomain: true,
  },
  {
    id: "cute-152",
    text: "Knowledge comes, but wisdom lingers.",
    author: "Alfred, Lord Tennyson",
    source: "Poems",
    sourceUrl: "https://www.gutenberg.org/ebooks/8601",
    placement: "review_on_track",
    tone: "reflective",
    publicDomain: true,
  },
  {
    id: "cute-155",
    text: "The proper function of man is to live, not to exist.",
    author: "Jack London",
    source: "Credo",
    sourceUrl: "https://london.sonoma.edu/writings/essays/credo.html",
    placement: "review_on_track",
    tone: "motivational",
    publicDomain: true,
  },
  {
    id: "cute-156",
    text: "There is nothing more deceptive than an obvious fact.",
    author: "Arthur Conan Doyle",
    source: "The Adventures of Sherlock Holmes",
    sourceUrl: "https://www.gutenberg.org/ebooks/1661",
    placement: "review_on_track",
    tone: "analytical",
    publicDomain: true,
  },
  {
    id: "cute-159",
    text: "We are always getting away from the present moment.",
    author: "H. G. Wells",
    source: "The Time Machine",
    sourceUrl: "https://www.gutenberg.org/ebooks/35",
    placement: "review_on_track",
    tone: "reflective",
    publicDomain: true,
  },
  {
    id: "cute-164",
    text: "The people must know before they can act.",
    author: "Ida B. Wells",
    source: "Southern Horrors / source record",
    placement: "review_on_track",
    tone: "analytical",
    publicDomain: true,
  },
  {
    id: "cute-165",
    text: "Failure is impossible.",
    author: "Susan B. Anthony",
    source: "86th-birthday address, 1906",
    placement: "review_on_track",
    tone: "motivational",
    publicDomain: true,
  },
  {
    id: "cute-168",
    text: "There is a tide in the affairs of men, which, taken at the flood, leads on to fortune.",
    author: "William Shakespeare",
    source: "Julius Caesar",
    sourceUrl: "https://www.gutenberg.org/ebooks/100",
    placement: "review_exceeded_expectations",
    tone: "triumphant",
    publicDomain: true,
  },
  {
    id: "cute-169",
    text: "There's a divinity that shapes our ends, rough-hew them how we will.",
    author: "William Shakespeare",
    source: "Hamlet",
    sourceUrl: "https://www.gutenberg.org/ebooks/100",
    placement: "review_exceeded_expectations",
    tone: "triumphant",
    publicDomain: true,
  },
  {
    id: "cute-170",
    text: "From a little spark may burst a flame.",
    author: "Dante Alighieri",
    source: "The Divine Comedy, Henry Wadsworth Longfellow translation",
    sourceUrl: "https://www.gutenberg.org/ebooks/8800",
    placement: "review_exceeded_expectations",
    tone: "celebratory",
    publicDomain: true,
  },
  {
    id: "cute-171",
    text: "The reward of a thing well done is having done it.",
    author: "Ralph Waldo Emerson",
    source: "Essays, First Series",
    sourceUrl: "https://www.gutenberg.org/ebooks/16643",
    placement: "review_exceeded_expectations",
    tone: "affirming",
    publicDomain: true,
  },
  {
    id: "cute-175",
    text: "I celebrate myself, and sing myself.",
    author: "Walt Whitman",
    source: "Leaves of Grass",
    sourceUrl: "https://www.gutenberg.org/ebooks/1322",
    placement: "review_exceeded_expectations",
    tone: "celebratory",
    publicDomain: true,
  },
  {
    id: "cute-178",
    text: "So many worlds, so much to do, so little done, such things to be.",
    author: "Alfred, Lord Tennyson",
    source: "Poems",
    sourceUrl: "https://www.gutenberg.org/ebooks/8601",
    placement: "review_exceeded_expectations",
    tone: "aspirational",
    publicDomain: true,
  },
  {
    id: "cute-181",
    text: "We have it in our power to begin the world over again.",
    author: "Thomas Paine",
    source: "Common Sense",
    sourceUrl: "https://www.gutenberg.org/ebooks/147",
    placement: "review_exceeded_expectations",
    tone: "triumphant",
    publicDomain: true,
  },
  {
    id: "cute-184",
    text: "To live will be an awfully big adventure.",
    author: "J. M. Barrie",
    source: "Peter Pan",
    sourceUrl: "https://www.gutenberg.org/ebooks/16",
    placement: "review_exceeded_expectations",
    tone: "playful",
    publicDomain: true,
  },
  {
    id: "cute-185",
    text: "I am satisfied\u2014I see, dance, laugh, sing.",
    author: "Walt Whitman",
    source: "Leaves of Grass",
    sourceUrl: "https://www.gutenberg.org/ebooks/1322",
    placement: "review_exceeded_expectations",
    tone: "celebratory",
    publicDomain: true,
  },
  {
    id: "cute-189",
    text: "Nothing great was ever achieved without enthusiasm.",
    author: "Ralph Waldo Emerson",
    source: "Essays, First Series",
    sourceUrl: "https://www.gutenberg.org/ebooks/16643",
    placement: "review_exceeded_expectations",
    tone: "celebratory",
    publicDomain: true,
  },
  {
    id: "cute-191",
    text: "Sweet are the uses of adversity.",
    author: "William Shakespeare",
    source: "As You Like It",
    sourceUrl: "https://www.gutenberg.org/ebooks/100",
    placement: "review_partial_disrupted",
    tone: "resilient",
    publicDomain: true,
  },
  {
    id: "cute-194",
    text: "There is nothing either good or bad, but thinking makes it so.",
    author: "William Shakespeare",
    source: "Hamlet",
    sourceUrl: "https://www.gutenberg.org/ebooks/100",
    placement: "review_partial_disrupted",
    tone: "reflective",
    publicDomain: true,
  },
  {
    id: "cute-195",
    text: "Better is one's own duty, though imperfectly performed, than the duty of another well performed.",
    author: "The Bhagavad Gita",
    source: "Sir Edwin Arnold translation",
    sourceUrl: "https://www.gutenberg.org/ebooks/2388",
    placement: "review_partial_disrupted",
    tone: "reassuring",
    publicDomain: true,
  },
  {
    id: "cute-196",
    text: "They also serve who only stand and wait.",
    author: "John Milton",
    source: "On His Blindness",
    sourceUrl: "https://www.gutenberg.org/ebooks/31706",
    placement: "review_partial_disrupted",
    tone: "reassuring",
    publicDomain: true,
  },
  {
    id: "cute-203",
    text: "Life appears to me too short to be spent in nursing animosity or registering wrongs.",
    author: "Charlotte Bront\u00eb",
    source: "Jane Eyre",
    sourceUrl: "https://www.gutenberg.org/ebooks/1260",
    placement: "review_partial_disrupted",
    tone: "reflective",
    publicDomain: true,
  },
  {
    id: "cute-204",
    text: "The way to right wrongs is to turn the light of truth upon them.",
    author: "Ida B. Wells",
    source: "The Light of Truth",
    placement: "review_partial_disrupted",
    tone: "serious",
    publicDomain: true,
  },
  {
    id: "cute-205",
    text: "Independence is happiness.",
    author: "Susan B. Anthony",
    source: "Susan B. Anthony source record",
    placement: "review_partial_disrupted",
    tone: "confident",
    publicDomain: true,
  },
  {
    id: "cute-207",
    text: "Nothing is so painful to the human mind as a great and sudden change.",
    author: "Mary Shelley",
    source: "Frankenstein",
    sourceUrl: "https://www.gutenberg.org/ebooks/84",
    placement: "review_partial_disrupted",
    tone: "serious",
    publicDomain: true,
  },
  {
    id: "cute-208",
    text: "We need never be ashamed of our tears.",
    author: "Charles Dickens",
    source: "Great Expectations",
    sourceUrl: "https://www.gutenberg.org/ebooks/1400",
    placement: "review_partial_disrupted",
    tone: "compassionate",
    publicDomain: true,
  },
  {
    id: "cute-211",
    text: "What's done cannot be undone.",
    author: "William Shakespeare",
    source: "Macbeth",
    sourceUrl: "https://www.gutenberg.org/ebooks/100",
    placement: "review_partial_disrupted",
    tone: "accepting",
    publicDomain: true,
  },
  {
    id: "cute-212",
    text: "We are all in the gutter, but some of us are looking at the stars.",
    author: "Oscar Wilde",
    source: "Lady Windermere's Fan",
    sourceUrl: "https://www.gutenberg.org/ebooks/790",
    placement: "review_partial_disrupted",
    tone: "hopeful",
    publicDomain: true,
  },
  {
    id: "cute-213",
    text: "Truth is powerful and it prevails.",
    author: "Sojourner Truth",
    source: "Book of Life / Angola remarks, 1863",
    placement: "review_partial_disrupted",
    tone: "serious",
    publicDomain: true,
  },
  {
    id: "cute-214",
    text: "How very little can be done under the spirit of fear.",
    author: "Florence Nightingale",
    source: "Florence Nightingale source record",
    placement: "review_partial_disrupted",
    tone: "reassuring",
    publicDomain: true,
  },
  {
    id: "cute-215",
    text: "The robbed that smiles steals something from the thief.",
    author: "William Shakespeare",
    source: "Othello",
    sourceUrl: "https://www.gutenberg.org/ebooks/100",
    placement: "review_partial_disrupted",
    tone: "resilient",
    publicDomain: true,
  },
  {
    id: "cute-219",
    text: "It is a capital mistake to theorize before one has data.",
    author: "Arthur Conan Doyle",
    source: "The Adventures of Sherlock Holmes",
    sourceUrl: "https://www.gutenberg.org/ebooks/1661",
    placement: "review_more_information",
    tone: "analytical",
    publicDomain: true,
  },
  {
    id: "cute-221",
    text: "The Analytical Engine weaves algebraic patterns just as the Jacquard loom weaves flowers and leaves.",
    author: "Ada Lovelace",
    source: "Notes on the Analytical Engine, 1843",
    placement: "review_more_information",
    tone: "analytical",
    publicDomain: true,
  },
  {
    id: "cute-223",
    text: "You see, but you do not observe.",
    author: "Arthur Conan Doyle",
    source: "The Adventures of Sherlock Holmes",
    sourceUrl: "https://www.gutenberg.org/ebooks/1661",
    placement: "review_more_information",
    tone: "analytical",
    publicDomain: true,
  },
  {
    id: "cute-229",
    text: "The truth is rarely pure and never simple.",
    author: "Oscar Wilde",
    source: "The Importance of Being Earnest",
    sourceUrl: "https://www.gutenberg.org/ebooks/844",
    placement: "review_more_information",
    tone: "witty",
    publicDomain: true,
  },
  {
    id: "cute-232",
    text: "There are mysteries which men can only guess at, which age by age they may solve only in part.",
    author: "Bram Stoker",
    source: "Dracula",
    sourceUrl: "https://www.gutenberg.org/ebooks/345",
    placement: "review_more_information",
    tone: "curious",
    publicDomain: true,
  },
  {
    id: "cute-233",
    text: "Any truth is better than indefinite doubt.",
    author: "Arthur Conan Doyle",
    source: "The Adventures of Sherlock Holmes",
    sourceUrl: "https://www.gutenberg.org/ebooks/1661",
    placement: "review_more_information",
    tone: "analytical",
    publicDomain: true,
  },
  {
    id: "cute-234",
    text: "When you have eliminated the impossible, whatever remains, however improbable, must be the truth.",
    author: "Arthur Conan Doyle",
    source: "The Adventures of Sherlock Holmes",
    sourceUrl: "https://www.gutenberg.org/ebooks/1661",
    placement: "review_more_information",
    tone: "analytical",
    publicDomain: true,
  },
  {
    id: "cute-235",
    text: "Reserving judgments is a matter of infinite hope.",
    author: "F. Scott Fitzgerald",
    source: "The Great Gatsby",
    sourceUrl: "https://en.wikisource.org/wiki/The_Great_Gatsby",
    placement: "review_more_information",
    tone: "restrained",
    publicDomain: true,
  },
  {
    id: "cute-242",
    text: "A foolish consistency is the hobgoblin of little minds.",
    author: "Ralph Waldo Emerson",
    source: "Essays, First Series",
    sourceUrl: "https://www.gutenberg.org/ebooks/16643",
    placement: "review_adjusting_harder",
    tone: "flexible",
    publicDomain: true,
  },
  {
    id: "cute-248",
    text: "I would always rather be happy than dignified.",
    author: "Charlotte Bront\u00eb",
    source: "Jane Eyre",
    sourceUrl: "https://www.gutenberg.org/ebooks/1260",
    placement: "review_adjusting_harder",
    tone: "self-compassionate",
    publicDomain: true,
  },
  {
    id: "cute-250",
    text: "The man who never alters his opinion is like standing water, and breeds reptiles of the mind.",
    author: "William Blake",
    source: "The Marriage of Heaven and Hell",
    sourceUrl: "https://www.gutenberg.org/ebooks/45315",
    placement: "review_adjusting_harder",
    tone: "flexible",
    publicDomain: true,
  },
  {
    id: "cute-251",
    text: "We aim above the mark to hit the mark.",
    author: "Ralph Waldo Emerson",
    source: "Essays, First Series",
    sourceUrl: "https://www.gutenberg.org/ebooks/16643",
    placement: "review_adjusting_harder",
    tone: "aspirational",
    publicDomain: true,
  },
  {
    id: "cute-253",
    text: "To define is to limit.",
    author: "Oscar Wilde",
    source: "The Picture of Dorian Gray",
    sourceUrl: "https://www.gutenberg.org/ebooks/174",
    placement: "review_adjusting_harder",
    tone: "concise",
    publicDomain: true,
  },
  {
    id: "cute-254",
    text: "The old order changeth, yielding place to new.",
    author: "Alfred, Lord Tennyson",
    source: "Idylls of the King",
    sourceUrl: "https://www.gutenberg.org/ebooks/8601",
    placement: "review_adjusting_harder",
    tone: "accepting",
    publicDomain: true,
  },
  {
    id: "cute-256",
    text: "Think only of the past as its remembrance gives you pleasure.",
    author: "Jane Austen",
    source: "Pride and Prejudice",
    sourceUrl: "https://www.gutenberg.org/ebooks/1342",
    placement: "review_adjusting_harder",
    tone: "reflective",
    publicDomain: true,
  },
  {
    id: "cute-257",
    text: "Were there none who were discontented, the world would never reach anything better.",
    author: "Florence Nightingale",
    source: "Florence Nightingale source record",
    placement: "review_adjusting_harder",
    tone: "motivational",
    publicDomain: true,
  },
  {
    id: "cute-258",
    text: "It is not easy to be a pioneer\u2014but oh, it is fascinating!",
    author: "Elizabeth Blackwell",
    source: "Pioneer Work in Opening the Medical Profession to Women",
    placement: "review_adjusting_harder",
    tone: "playful",
    publicDomain: true,
  },
  {
    id: "cute-259",
    text: "To expect the unexpected shows a thoroughly modern intellect.",
    author: "Oscar Wilde",
    source: "An Ideal Husband",
    sourceUrl: "https://www.gutenberg.org/ebooks/885",
    placement: "review_adjusting_harder",
    tone: "witty",
    publicDomain: true,
  },
  {
    id: "cute-264",
    text: "No need to hurry. No need to sparkle. No need to be anybody but oneself.",
    author: "Virginia Woolf",
    source: "A Room of One's Own",
    sourceUrl: "https://gutenberg.net.au/ebooks02/0200791h.html",
    placement: "review_pain_recovery",
    tone: "gentle",
    publicDomain: true,
  },
  {
    id: "cute-271",
    text: "I care for myself. The more solitary, the more friendless, the more unsustained I am, the more I will respect myself.",
    author: "Charlotte Bront\u00eb",
    source: "Jane Eyre",
    sourceUrl: "https://www.gutenberg.org/ebooks/1260",
    placement: "review_pain_recovery",
    tone: "self-compassionate",
    publicDomain: true,
  },
  {
    id: "cute-272",
    text: "Apprehension, uncertainty, waiting, expectation, fear of surprise, do a patient more harm than any exertion.",
    author: "Florence Nightingale",
    source: "Notes on Nursing",
    placement: "review_pain_recovery",
    tone: "serious",
    publicDomain: true,
  },
  {
    id: "cute-273",
    text: "Health has its science, as well as disease.",
    author: "Elizabeth Blackwell",
    source: "Medicine as a Profession for Women, 1860",
    placement: "review_pain_recovery",
    tone: "serious",
    publicDomain: true,
  },
  {
    id: "cute-274",
    text: "No man knows till he has suffered from the night how sweet and dear to his heart and eye the morning can be.",
    author: "Bram Stoker",
    source: "Dracula",
    sourceUrl: "https://www.gutenberg.org/ebooks/345",
    placement: "review_pain_recovery",
    tone: "hopeful",
    publicDomain: true,
  },
  {
    id: "cute-277",
    text: "How poor are they that have not patience! What wound did ever heal but by degrees?",
    author: "William Shakespeare",
    source: "Othello",
    sourceUrl: "https://www.gutenberg.org/ebooks/100",
    placement: "review_pain_recovery",
    tone: "patient",
    publicDomain: true,
  },
  {
    id: "cute-278",
    text: "There is no charm equal to tenderness of heart.",
    author: "Jane Austen",
    source: "Emma",
    sourceUrl: "https://www.gutenberg.org/ebooks/158",
    placement: "review_pain_recovery",
    tone: "gentle",
    publicDomain: true,
  },
  {
    id: "cute-282",
    text: "Have regular hours for work and play; make each day both useful and pleasant.",
    author: "Louisa May Alcott",
    source: "Little Women",
    sourceUrl: "https://www.gutenberg.org/ebooks/514",
    placement: "review_schedule_fit",
    tone: "balanced",
    publicDomain: true,
  },
  {
    id: "cute-285",
    text: "Time will explain.",
    author: "Jane Austen",
    source: "Persuasion",
    sourceUrl: "https://www.gutenberg.org/ebooks/105",
    placement: "review_schedule_fit",
    tone: "patient",
    publicDomain: true,
  },
  {
    id: "cute-288",
    text: "Drive thy business; let not that drive thee.",
    author: "Benjamin Franklin",
    source: "Poor Richard's Almanack",
    sourceUrl: "https://en.wikisource.org/wiki/Poor_Richard%27s_Almanack",
    placement: "review_schedule_fit",
    tone: "balanced",
    publicDomain: true,
  },
  {
    id: "cute-293",
    text: "If a thing is worth doing, it is worth doing badly.",
    author: "G. K. Chesterton",
    source: "What's Wrong with the World",
    sourceUrl: "https://www.gutenberg.org/ebooks/386",
    placement: "review_schedule_fit",
    tone: "pragmatic",
    publicDomain: true,
  },
  {
    id: "cute-297",
    text: "To travel hopefully is a better thing than to arrive, and the true success is to labour.",
    author: "Robert Louis Stevenson",
    source: "Virginibus Puerisque: El Dorado",
    sourceUrl: "https://www.gutenberg.org/ebooks/1717",
    placement: "review_schedule_fit",
    tone: "patient",
    publicDomain: true,
  },
] as const;
// Counts: {"program_overview_before_starting": 11, "review_adjusting_harder": 10, "review_exceeded_expectations": 10, "review_more_information": 8, "review_on_track": 13, "review_pain_recovery": 7, "review_partial_disrupted": 14, "review_schedule_fit": 5, "workout_cardio_health": 11, "workout_general": 15, "workout_strength_hypertrophy": 10}
