import type {
  ChoiceCandidate,
  Equipment,
  ExerciseDefinition,
  ExercisePurpose,
  MovementPattern,
  Muscle,
  QuestionnaireInput,
} from "./types.js";

const exercise = (definition: ExerciseDefinition): ExerciseDefinition =>
  definition;

export const EXERCISES: ExerciseDefinition[] = [
  exercise({
    id: "competition_squat",
    name: "Competition squat",
    patterns: ["squat"],
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings", "trunk"],
    equipmentAlternatives: [["barbell", "rack", "plates"]],
    exerciseClass: "competition",
    purposes: ["competition_skill", "strength"],
    lift: "squat",
    specificity: 3,
    fatigue: 3,
    alternatives: ["high_bar_squat", "safety_bar_squat"],
  }),
  exercise({
    id: "high_bar_squat",
    name: "High-bar squat",
    patterns: ["squat"],
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["trunk"],
    equipmentAlternatives: [["barbell", "rack", "plates"]],
    exerciseClass: "compound",
    purposes: ["strength", "hypertrophy"],
    lift: "squat",
    specificity: 2,
    fatigue: 3,
    alternatives: [
      "competition_squat",
      "front_squat",
      "hack_squat",
      "goblet_squat",
    ],
  }),
  exercise({
    id: "front_squat",
    name: "Front squat",
    patterns: ["squat"],
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["trunk"],
    equipmentAlternatives: [["barbell", "rack", "plates"]],
    exerciseClass: "compound",
    purposes: ["strength", "hypertrophy"],
    specificity: 1,
    fatigue: 3,
    alternatives: ["high_bar_squat", "hack_squat", "goblet_squat"],
  }),
  exercise({
    id: "safety_bar_squat",
    name: "Safety-bar squat",
    patterns: ["squat"],
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["trunk"],
    equipmentAlternatives: [["barbell", "rack", "plates"]],
    exerciseClass: "compound",
    purposes: ["strength", "hypertrophy"],
    lift: "squat",
    specificity: 2,
    fatigue: 3,
    alternatives: ["competition_squat", "high_bar_squat", "hack_squat"],
  }),
  exercise({
    id: "hack_squat",
    name: "Hack squat",
    patterns: ["squat"],
    primaryMuscles: ["quads"],
    secondaryMuscles: ["glutes"],
    equipmentAlternatives: [["machines"]],
    exerciseClass: "stable_compound",
    purposes: ["hypertrophy", "low_fatigue_volume"],
    specificity: 0,
    fatigue: 2,
    alternatives: ["leg_press", "goblet_squat", "split_squat"],
  }),
  exercise({
    id: "leg_press",
    name: "Leg press",
    patterns: ["squat"],
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: [],
    equipmentAlternatives: [["machines"]],
    exerciseClass: "stable_compound",
    purposes: ["hypertrophy", "low_fatigue_volume"],
    specificity: 0,
    fatigue: 2,
    alternatives: ["hack_squat", "goblet_squat", "split_squat"],
  }),
  exercise({
    id: "smith_squat",
    name: "Smith-machine squat",
    patterns: ["squat"],
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings", "trunk"],
    equipmentAlternatives: [["smith_machine", "plates"]],
    exerciseClass: "stable_compound",
    purposes: ["strength", "hypertrophy", "low_fatigue_volume"],
    lift: "squat",
    specificity: 1,
    fatigue: 2,
    alternatives: ["high_bar_squat", "hack_squat", "leg_press", "goblet_squat"],
  }),
  exercise({
    id: "goblet_squat",
    name: "Goblet squat",
    patterns: ["squat"],
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["trunk"],
    equipmentAlternatives: [["dumbbells"]],
    exerciseClass: "compound",
    purposes: ["hypertrophy", "general_function"],
    specificity: 0,
    fatigue: 2,
    alternatives: ["split_squat", "step_up", "leg_press"],
  }),
  exercise({
    id: "split_squat",
    name: "Dumbbell split squat",
    patterns: ["squat"],
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings"],
    equipmentAlternatives: [["dumbbells"]],
    exerciseClass: "compound",
    purposes: ["hypertrophy", "general_function"],
    specificity: 0,
    fatigue: 2,
    unilateral: true,
    alternatives: ["goblet_squat", "step_up", "leg_press"],
  }),
  exercise({
    id: "step_up",
    name: "Dumbbell step-up",
    patterns: ["squat"],
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings"],
    equipmentAlternatives: [["dumbbells", "bench"]],
    exerciseClass: "compound",
    purposes: ["hypertrophy", "general_function"],
    specificity: 0,
    fatigue: 2,
    unilateral: true,
    alternatives: ["split_squat", "goblet_squat"],
  }),
  exercise({
    id: "leg_extension",
    name: "Leg extension",
    patterns: ["squat"],
    primaryMuscles: ["quads"],
    secondaryMuscles: [],
    equipmentAlternatives: [["machines"]],
    exerciseClass: "isolation",
    purposes: ["hypertrophy", "low_fatigue_volume"],
    specificity: 0,
    fatigue: 1,
    alternatives: ["hack_squat", "heel_elevated_squat"],
  }),
  exercise({
    id: "heel_elevated_squat",
    name: "Heel-elevated dumbbell squat",
    patterns: ["squat"],
    primaryMuscles: ["quads"],
    secondaryMuscles: ["glutes"],
    equipmentAlternatives: [["dumbbells"]],
    exerciseClass: "compound",
    purposes: ["hypertrophy"],
    specificity: 0,
    fatigue: 2,
    partialSubstitute: true,
    alternatives: ["leg_extension", "goblet_squat"],
  }),

  exercise({
    id: "competition_bench",
    name: "Competition bench press",
    patterns: ["horizontal_push"],
    primaryMuscles: ["chest"],
    secondaryMuscles: ["triceps", "front_delts"],
    equipmentAlternatives: [["barbell", "bench", "rack", "plates"]],
    exerciseClass: "competition",
    purposes: ["competition_skill", "strength"],
    lift: "bench",
    specificity: 3,
    fatigue: 2,
    alternatives: ["pause_bench", "close_grip_bench", "dumbbell_bench"],
  }),
  exercise({
    id: "pause_bench",
    name: "Paused bench press",
    patterns: ["horizontal_push"],
    primaryMuscles: ["chest"],
    secondaryMuscles: ["triceps", "front_delts"],
    equipmentAlternatives: [["barbell", "bench", "rack", "plates"]],
    exerciseClass: "compound",
    purposes: ["competition_skill", "strength"],
    lift: "bench",
    specificity: 2,
    fatigue: 2,
    alternatives: ["competition_bench", "close_grip_bench", "dumbbell_bench"],
  }),
  exercise({
    id: "close_grip_bench",
    name: "Close-grip bench press",
    patterns: ["horizontal_push"],
    primaryMuscles: ["triceps", "chest"],
    secondaryMuscles: ["front_delts"],
    equipmentAlternatives: [["barbell", "bench", "rack", "plates"]],
    exerciseClass: "compound",
    purposes: ["strength", "hypertrophy"],
    lift: "bench",
    specificity: 2,
    fatigue: 2,
    alternatives: [
      "competition_bench",
      "dumbbell_bench",
      "machine_chest_press",
    ],
  }),
  exercise({
    id: "dumbbell_bench",
    name: "Dumbbell bench press",
    patterns: ["horizontal_push"],
    primaryMuscles: ["chest"],
    secondaryMuscles: ["triceps", "front_delts"],
    equipmentAlternatives: [["dumbbells", "bench"]],
    exerciseClass: "stable_compound",
    purposes: ["hypertrophy", "strength"],
    specificity: 0,
    fatigue: 2,
    alternatives: ["machine_chest_press", "push_up", "dumbbell_floor_press"],
  }),
  exercise({
    id: "dumbbell_floor_press",
    name: "Dumbbell floor press",
    patterns: ["horizontal_push"],
    primaryMuscles: ["chest", "triceps"],
    secondaryMuscles: ["front_delts"],
    equipmentAlternatives: [["dumbbells"]],
    exerciseClass: "stable_compound",
    purposes: ["hypertrophy", "strength"],
    specificity: 0,
    fatigue: 2,
    partialSubstitute: true,
    alternatives: ["dumbbell_bench", "push_up"],
  }),
  exercise({
    id: "incline_dumbbell_press",
    name: "Incline dumbbell press",
    patterns: ["horizontal_push"],
    primaryMuscles: ["upper_chest"],
    secondaryMuscles: ["triceps", "front_delts"],
    equipmentAlternatives: [["dumbbells", "bench"]],
    exerciseClass: "stable_compound",
    purposes: ["hypertrophy"],
    specificity: 0,
    fatigue: 2,
    alternatives: ["incline_machine_press", "feet_elevated_push_up"],
  }),
  exercise({
    id: "machine_chest_press",
    name: "Machine chest press",
    patterns: ["horizontal_push"],
    primaryMuscles: ["chest"],
    secondaryMuscles: ["triceps", "front_delts"],
    equipmentAlternatives: [["machines"]],
    exerciseClass: "stable_compound",
    purposes: ["hypertrophy", "low_fatigue_volume"],
    specificity: 0,
    fatigue: 1,
    alternatives: ["dumbbell_bench", "push_up"],
  }),
  exercise({
    id: "smith_bench",
    name: "Smith-machine bench press",
    patterns: ["horizontal_push"],
    primaryMuscles: ["chest"],
    secondaryMuscles: ["triceps", "front_delts"],
    equipmentAlternatives: [["smith_machine", "bench", "plates"]],
    exerciseClass: "stable_compound",
    purposes: ["strength", "hypertrophy", "low_fatigue_volume"],
    lift: "bench",
    specificity: 1,
    fatigue: 1,
    alternatives: [
      "competition_bench",
      "dumbbell_bench",
      "machine_chest_press",
    ],
  }),
  exercise({
    id: "incline_machine_press",
    name: "Incline machine press",
    patterns: ["horizontal_push"],
    primaryMuscles: ["upper_chest"],
    secondaryMuscles: ["triceps", "front_delts"],
    equipmentAlternatives: [["machines"]],
    exerciseClass: "stable_compound",
    purposes: ["hypertrophy", "low_fatigue_volume"],
    specificity: 0,
    fatigue: 1,
    alternatives: ["incline_dumbbell_press", "feet_elevated_push_up"],
  }),
  exercise({
    id: "push_up",
    name: "Push-up",
    patterns: ["horizontal_push"],
    primaryMuscles: ["chest"],
    secondaryMuscles: ["triceps", "front_delts"],
    equipmentAlternatives: [[]],
    exerciseClass: "stable_compound",
    purposes: ["hypertrophy", "general_function"],
    specificity: 0,
    fatigue: 1,
    loadType: "added_to_bodyweight",
    alternatives: ["dumbbell_floor_press", "machine_chest_press"],
  }),
  exercise({
    id: "feet_elevated_push_up",
    name: "Feet-elevated push-up",
    patterns: ["horizontal_push"],
    primaryMuscles: ["upper_chest"],
    secondaryMuscles: ["triceps", "front_delts"],
    equipmentAlternatives: [["bench"]],
    exerciseClass: "stable_compound",
    purposes: ["hypertrophy"],
    specificity: 0,
    fatigue: 1,
    loadType: "added_to_bodyweight",
    alternatives: ["incline_dumbbell_press", "push_up"],
  }),
  exercise({
    id: "cable_fly",
    name: "Cable fly",
    patterns: ["horizontal_push"],
    primaryMuscles: ["chest"],
    secondaryMuscles: [],
    equipmentAlternatives: [["cables"]],
    exerciseClass: "isolation",
    purposes: ["hypertrophy", "low_fatigue_volume"],
    specificity: 0,
    fatigue: 1,
    alternatives: ["pec_deck", "dumbbell_fly"],
  }),
  exercise({
    id: "pec_deck",
    name: "Pec deck",
    patterns: ["horizontal_push"],
    primaryMuscles: ["chest"],
    secondaryMuscles: [],
    equipmentAlternatives: [["machines"]],
    exerciseClass: "isolation",
    purposes: ["hypertrophy", "low_fatigue_volume"],
    specificity: 0,
    fatigue: 1,
    alternatives: ["cable_fly", "dumbbell_fly"],
  }),
  exercise({
    id: "dumbbell_fly",
    name: "Dumbbell fly",
    patterns: ["horizontal_push"],
    primaryMuscles: ["chest"],
    secondaryMuscles: [],
    equipmentAlternatives: [["dumbbells", "bench"]],
    exerciseClass: "isolation",
    purposes: ["hypertrophy"],
    specificity: 0,
    fatigue: 1,
    alternatives: ["cable_fly", "pec_deck"],
  }),

  exercise({
    id: "competition_deadlift",
    name: "Competition deadlift",
    patterns: ["hinge"],
    primaryMuscles: ["glutes", "hamstrings"],
    secondaryMuscles: ["upper_back", "trunk"],
    equipmentAlternatives: [["barbell", "plates"]],
    exerciseClass: "competition",
    purposes: ["competition_skill", "strength"],
    lift: "deadlift",
    specificity: 3,
    fatigue: 3,
    alternatives: ["paused_deadlift", "barbell_rdl", "dumbbell_rdl"],
  }),
  exercise({
    id: "paused_deadlift",
    name: "Paused deadlift",
    patterns: ["hinge"],
    primaryMuscles: ["glutes", "hamstrings"],
    secondaryMuscles: ["upper_back", "trunk"],
    equipmentAlternatives: [["barbell", "plates"]],
    exerciseClass: "compound",
    purposes: ["competition_skill", "strength"],
    lift: "deadlift",
    specificity: 2,
    fatigue: 3,
    alternatives: ["competition_deadlift", "barbell_rdl"],
  }),
  exercise({
    id: "barbell_rdl",
    name: "Barbell Romanian deadlift",
    patterns: ["hinge"],
    primaryMuscles: ["hamstrings", "glutes"],
    secondaryMuscles: ["upper_back", "trunk"],
    equipmentAlternatives: [["barbell", "plates"]],
    exerciseClass: "compound",
    purposes: ["strength", "hypertrophy"],
    specificity: 1,
    fatigue: 3,
    alternatives: ["dumbbell_rdl", "back_extension", "hip_thrust"],
  }),
  exercise({
    id: "smith_rdl",
    name: "Smith-machine Romanian deadlift",
    patterns: ["hinge"],
    primaryMuscles: ["hamstrings", "glutes"],
    secondaryMuscles: ["upper_back", "trunk"],
    equipmentAlternatives: [["smith_machine", "plates"]],
    exerciseClass: "stable_compound",
    purposes: ["strength", "hypertrophy", "low_fatigue_volume"],
    lift: "deadlift",
    specificity: 1,
    fatigue: 2,
    alternatives: [
      "barbell_rdl",
      "dumbbell_rdl",
      "back_extension",
      "hip_thrust",
    ],
  }),
  exercise({
    id: "dumbbell_rdl",
    name: "Dumbbell Romanian deadlift",
    patterns: ["hinge"],
    primaryMuscles: ["hamstrings", "glutes"],
    secondaryMuscles: ["trunk"],
    equipmentAlternatives: [["dumbbells"]],
    exerciseClass: "compound",
    purposes: ["hypertrophy", "general_function"],
    specificity: 0,
    fatigue: 2,
    alternatives: ["barbell_rdl", "single_leg_rdl", "hip_thrust"],
  }),
  exercise({
    id: "single_leg_rdl",
    name: "Single-leg dumbbell RDL",
    patterns: ["hinge"],
    primaryMuscles: ["hamstrings", "glutes"],
    secondaryMuscles: ["trunk"],
    equipmentAlternatives: [["dumbbells"]],
    exerciseClass: "compound",
    purposes: ["hypertrophy", "general_function"],
    specificity: 0,
    fatigue: 2,
    unilateral: true,
    alternatives: ["dumbbell_rdl", "back_extension"],
  }),
  exercise({
    id: "hip_thrust",
    name: "Hip thrust",
    patterns: ["hinge"],
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["hamstrings"],
    equipmentAlternatives: [
      ["barbell", "bench", "plates"],
      ["dumbbells", "bench"],
      ["machines"],
    ],
    exerciseClass: "stable_compound",
    purposes: ["hypertrophy", "low_fatigue_volume"],
    specificity: 0,
    fatigue: 2,
    alternatives: ["glute_bridge", "dumbbell_rdl"],
  }),
  exercise({
    id: "glute_bridge",
    name: "Loaded glute bridge",
    patterns: ["hinge"],
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["hamstrings"],
    equipmentAlternatives: [["dumbbells"], ["barbell", "plates"]],
    exerciseClass: "stable_compound",
    purposes: ["hypertrophy", "general_function"],
    specificity: 0,
    fatigue: 1,
    alternatives: ["hip_thrust", "dumbbell_rdl"],
  }),
  exercise({
    id: "back_extension",
    name: "Back extension",
    patterns: ["hinge"],
    primaryMuscles: ["glutes", "hamstrings"],
    secondaryMuscles: ["trunk"],
    equipmentAlternatives: [["machines"]],
    exerciseClass: "stable_compound",
    purposes: ["hypertrophy", "low_fatigue_volume"],
    specificity: 0,
    fatigue: 2,
    alternatives: ["dumbbell_rdl", "hip_thrust"],
  }),
  exercise({
    id: "leg_curl",
    name: "Leg curl",
    patterns: ["knee_flexion"],
    primaryMuscles: ["hamstrings"],
    secondaryMuscles: [],
    equipmentAlternatives: [["machines"]],
    exerciseClass: "isolation",
    purposes: ["hypertrophy", "low_fatigue_volume"],
    specificity: 0,
    fatigue: 1,
    alternatives: ["slider_leg_curl", "dumbbell_leg_curl"],
  }),
  exercise({
    id: "slider_leg_curl",
    name: "Slider leg curl",
    patterns: ["knee_flexion"],
    primaryMuscles: ["hamstrings"],
    secondaryMuscles: ["glutes"],
    equipmentAlternatives: [[]],
    exerciseClass: "isolation",
    purposes: ["hypertrophy", "general_function"],
    specificity: 0,
    fatigue: 1,
    partialSubstitute: true,
    loadType: "added_to_bodyweight",
    alternatives: ["leg_curl", "dumbbell_leg_curl"],
  }),
  exercise({
    id: "dumbbell_leg_curl",
    name: "Dumbbell leg curl",
    patterns: ["knee_flexion"],
    primaryMuscles: ["hamstrings"],
    secondaryMuscles: [],
    equipmentAlternatives: [["dumbbells", "bench"]],
    exerciseClass: "isolation",
    purposes: ["hypertrophy"],
    specificity: 0,
    fatigue: 1,
    partialSubstitute: true,
    alternatives: ["leg_curl", "slider_leg_curl"],
  }),

  exercise({
    id: "overhead_press",
    name: "Barbell overhead press",
    patterns: ["vertical_push"],
    primaryMuscles: ["front_delts"],
    secondaryMuscles: ["triceps"],
    equipmentAlternatives: [["barbell", "rack", "plates"]],
    exerciseClass: "compound",
    purposes: ["strength", "hypertrophy"],
    specificity: 0,
    fatigue: 2,
    alternatives: ["dumbbell_overhead_press", "machine_shoulder_press"],
  }),
  exercise({
    id: "dumbbell_overhead_press",
    name: "Dumbbell overhead press",
    patterns: ["vertical_push"],
    primaryMuscles: ["front_delts"],
    secondaryMuscles: ["triceps"],
    equipmentAlternatives: [["dumbbells"]],
    exerciseClass: "stable_compound",
    purposes: ["hypertrophy", "strength"],
    specificity: 0,
    fatigue: 2,
    alternatives: ["machine_shoulder_press", "pike_push_up"],
  }),
  exercise({
    id: "machine_shoulder_press",
    name: "Machine shoulder press",
    patterns: ["vertical_push"],
    primaryMuscles: ["front_delts"],
    secondaryMuscles: ["triceps"],
    equipmentAlternatives: [["machines"]],
    exerciseClass: "stable_compound",
    purposes: ["hypertrophy", "low_fatigue_volume"],
    specificity: 0,
    fatigue: 1,
    alternatives: ["dumbbell_overhead_press", "pike_push_up"],
  }),
  exercise({
    id: "pike_push_up",
    name: "Pike push-up",
    patterns: ["vertical_push"],
    primaryMuscles: ["front_delts"],
    secondaryMuscles: ["triceps"],
    equipmentAlternatives: [[]],
    exerciseClass: "stable_compound",
    purposes: ["hypertrophy", "general_function"],
    specificity: 0,
    fatigue: 1,
    loadType: "added_to_bodyweight",
    alternatives: ["dumbbell_overhead_press"],
  }),
  exercise({
    id: "dumbbell_lateral_raise",
    name: "Dumbbell lateral raise",
    patterns: ["lateral_raise"],
    primaryMuscles: ["side_delts"],
    secondaryMuscles: [],
    equipmentAlternatives: [["dumbbells"]],
    exerciseClass: "isolation",
    purposes: ["hypertrophy", "low_fatigue_volume"],
    specificity: 0,
    fatigue: 1,
    alternatives: ["cable_lateral_raise", "machine_lateral_raise"],
  }),
  exercise({
    id: "cable_lateral_raise",
    name: "Cable lateral raise",
    patterns: ["lateral_raise"],
    primaryMuscles: ["side_delts"],
    secondaryMuscles: [],
    equipmentAlternatives: [["cables"]],
    exerciseClass: "isolation",
    purposes: ["hypertrophy", "low_fatigue_volume"],
    specificity: 0,
    fatigue: 1,
    alternatives: ["dumbbell_lateral_raise", "machine_lateral_raise"],
  }),
  exercise({
    id: "machine_lateral_raise",
    name: "Machine lateral raise",
    patterns: ["lateral_raise"],
    primaryMuscles: ["side_delts"],
    secondaryMuscles: [],
    equipmentAlternatives: [["machines"]],
    exerciseClass: "isolation",
    purposes: ["hypertrophy", "low_fatigue_volume"],
    specificity: 0,
    fatigue: 1,
    alternatives: ["dumbbell_lateral_raise", "cable_lateral_raise"],
  }),

  exercise({
    id: "pull_up",
    name: "Pull-up",
    patterns: ["vertical_pull"],
    primaryMuscles: ["lats"],
    secondaryMuscles: ["biceps", "upper_back"],
    equipmentAlternatives: [["pullup_bar"]],
    exerciseClass: "compound",
    purposes: ["strength", "hypertrophy", "general_function"],
    specificity: 0,
    fatigue: 2,
    loadType: "added_to_bodyweight",
    alternatives: ["lat_pulldown", "dumbbell_pullover"],
  }),
  exercise({
    id: "lat_pulldown",
    name: "Lat pulldown",
    patterns: ["vertical_pull"],
    primaryMuscles: ["lats"],
    secondaryMuscles: ["biceps"],
    equipmentAlternatives: [["cables"], ["machines"]],
    exerciseClass: "stable_compound",
    purposes: ["hypertrophy", "low_fatigue_volume"],
    specificity: 0,
    fatigue: 1,
    alternatives: ["pull_up", "dumbbell_pullover"],
  }),
  exercise({
    id: "dumbbell_pullover",
    name: "Dumbbell pullover",
    patterns: ["vertical_pull"],
    primaryMuscles: ["lats"],
    secondaryMuscles: ["chest"],
    equipmentAlternatives: [["dumbbells", "bench"]],
    exerciseClass: "isolation",
    purposes: ["hypertrophy"],
    specificity: 0,
    fatigue: 1,
    partialSubstitute: true,
    alternatives: ["lat_pulldown", "pull_up"],
  }),
  exercise({
    id: "barbell_row",
    name: "Barbell row",
    patterns: ["horizontal_pull"],
    primaryMuscles: ["upper_back", "lats"],
    secondaryMuscles: ["biceps", "trunk"],
    equipmentAlternatives: [["barbell", "plates"]],
    exerciseClass: "compound",
    purposes: ["strength", "hypertrophy"],
    specificity: 0,
    fatigue: 3,
    alternatives: ["chest_supported_row", "one_arm_dumbbell_row", "cable_row"],
  }),
  exercise({
    id: "chest_supported_row",
    name: "Chest-supported dumbbell row",
    patterns: ["horizontal_pull"],
    primaryMuscles: ["upper_back", "lats"],
    secondaryMuscles: ["biceps", "rear_delts"],
    equipmentAlternatives: [["dumbbells", "bench"], ["machines"]],
    exerciseClass: "stable_compound",
    purposes: ["hypertrophy", "low_fatigue_volume"],
    specificity: 0,
    fatigue: 1,
    alternatives: ["one_arm_dumbbell_row", "cable_row", "machine_row"],
  }),
  exercise({
    id: "one_arm_dumbbell_row",
    name: "One-arm dumbbell row",
    patterns: ["horizontal_pull"],
    primaryMuscles: ["lats", "upper_back"],
    secondaryMuscles: ["biceps", "rear_delts"],
    equipmentAlternatives: [["dumbbells", "bench"]],
    exerciseClass: "compound",
    purposes: ["hypertrophy", "strength"],
    specificity: 0,
    fatigue: 2,
    unilateral: true,
    alternatives: ["chest_supported_row", "cable_row"],
  }),
  exercise({
    id: "cable_row",
    name: "Seated cable row",
    patterns: ["horizontal_pull"],
    primaryMuscles: ["upper_back", "lats"],
    secondaryMuscles: ["biceps", "rear_delts"],
    equipmentAlternatives: [["cables"]],
    exerciseClass: "stable_compound",
    purposes: ["hypertrophy", "low_fatigue_volume"],
    specificity: 0,
    fatigue: 1,
    alternatives: ["machine_row", "chest_supported_row"],
  }),
  exercise({
    id: "machine_row",
    name: "Machine row",
    patterns: ["horizontal_pull"],
    primaryMuscles: ["upper_back", "lats"],
    secondaryMuscles: ["biceps", "rear_delts"],
    equipmentAlternatives: [["machines"]],
    exerciseClass: "stable_compound",
    purposes: ["hypertrophy", "low_fatigue_volume"],
    specificity: 0,
    fatigue: 1,
    alternatives: ["cable_row", "chest_supported_row"],
  }),

  exercise({
    id: "dumbbell_curl",
    name: "Dumbbell curl",
    patterns: ["elbow_flexion"],
    primaryMuscles: ["biceps"],
    secondaryMuscles: [],
    equipmentAlternatives: [["dumbbells"]],
    exerciseClass: "isolation",
    purposes: ["hypertrophy", "low_fatigue_volume"],
    specificity: 0,
    fatigue: 1,
    alternatives: ["cable_curl", "machine_curl"],
  }),
  exercise({
    id: "cable_curl",
    name: "Cable curl",
    patterns: ["elbow_flexion"],
    primaryMuscles: ["biceps"],
    secondaryMuscles: [],
    equipmentAlternatives: [["cables"]],
    exerciseClass: "isolation",
    purposes: ["hypertrophy", "low_fatigue_volume"],
    specificity: 0,
    fatigue: 1,
    alternatives: ["dumbbell_curl", "machine_curl"],
  }),
  exercise({
    id: "machine_curl",
    name: "Machine curl",
    patterns: ["elbow_flexion"],
    primaryMuscles: ["biceps"],
    secondaryMuscles: [],
    equipmentAlternatives: [["machines"]],
    exerciseClass: "isolation",
    purposes: ["hypertrophy", "low_fatigue_volume"],
    specificity: 0,
    fatigue: 1,
    alternatives: ["dumbbell_curl", "cable_curl"],
  }),
  exercise({
    id: "triceps_pressdown",
    name: "Triceps pressdown",
    patterns: ["elbow_extension"],
    primaryMuscles: ["triceps"],
    secondaryMuscles: [],
    equipmentAlternatives: [["cables"]],
    exerciseClass: "isolation",
    purposes: ["hypertrophy", "low_fatigue_volume"],
    specificity: 0,
    fatigue: 1,
    alternatives: ["dumbbell_triceps_extension", "close_grip_push_up"],
  }),
  exercise({
    id: "dumbbell_triceps_extension",
    name: "Dumbbell overhead triceps extension",
    patterns: ["elbow_extension"],
    primaryMuscles: ["triceps"],
    secondaryMuscles: [],
    equipmentAlternatives: [["dumbbells"]],
    exerciseClass: "isolation",
    purposes: ["hypertrophy", "low_fatigue_volume"],
    specificity: 0,
    fatigue: 1,
    alternatives: ["triceps_pressdown", "close_grip_push_up"],
  }),
  exercise({
    id: "close_grip_push_up",
    name: "Close-grip push-up",
    patterns: ["elbow_extension", "horizontal_push"],
    primaryMuscles: ["triceps"],
    secondaryMuscles: ["chest"],
    equipmentAlternatives: [[]],
    exerciseClass: "stable_compound",
    purposes: ["hypertrophy", "general_function"],
    specificity: 0,
    fatigue: 1,
    loadType: "added_to_bodyweight",
    alternatives: ["dumbbell_triceps_extension", "triceps_pressdown"],
  }),
  exercise({
    id: "calf_raise",
    name: "Calf raise",
    patterns: ["calf_raise"],
    primaryMuscles: ["calves"],
    secondaryMuscles: [],
    equipmentAlternatives: [["machines"], ["dumbbells"], []],
    exerciseClass: "isolation",
    purposes: ["hypertrophy", "general_function"],
    specificity: 0,
    fatigue: 1,
    alternatives: [],
  }),
  exercise({
    id: "plank",
    name: "Plank",
    patterns: ["trunk"],
    primaryMuscles: ["trunk"],
    secondaryMuscles: [],
    equipmentAlternatives: [[]],
    exerciseClass: "trunk",
    purposes: ["trunk", "general_function"],
    specificity: 0,
    fatigue: 1,
    loadType: "added_to_bodyweight",
    alternatives: ["dead_bug", "suitcase_carry"],
  }),
  exercise({
    id: "dead_bug",
    name: "Dead bug",
    patterns: ["trunk"],
    primaryMuscles: ["trunk"],
    secondaryMuscles: [],
    equipmentAlternatives: [[]],
    exerciseClass: "trunk",
    purposes: ["trunk", "general_function"],
    specificity: 0,
    fatigue: 1,
    loadType: "added_to_bodyweight",
    alternatives: ["plank", "suitcase_carry"],
  }),
  exercise({
    id: "suitcase_carry",
    name: "Suitcase carry",
    patterns: ["carry", "trunk"],
    primaryMuscles: ["trunk"],
    secondaryMuscles: ["upper_back"],
    equipmentAlternatives: [["dumbbells"]],
    exerciseClass: "trunk",
    purposes: ["trunk", "general_function"],
    specificity: 0,
    fatigue: 1,
    alternatives: ["plank", "dead_bug"],
  }),
  exercise({
    id: "supported_balance",
    name: "Supported single-leg balance",
    patterns: ["locomotion"],
    primaryMuscles: [],
    secondaryMuscles: [],
    equipmentAlternatives: [[]],
    exerciseClass: "trunk",
    purposes: ["general_function"],
    specificity: 0,
    fatigue: 1,
    alternatives: [],
  }),
  exercise({
    id: "chair_stand",
    name: "Chair stand",
    patterns: ["squat"],
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["trunk"],
    equipmentAlternatives: [[]],
    exerciseClass: "stable_compound",
    purposes: ["general_function"],
    specificity: 0,
    fatigue: 1,
    alternatives: ["goblet_squat", "step_up"],
  }),
  exercise({
    id: "floor_transfer_practice",
    name: "Supported floor-transfer practice",
    patterns: ["locomotion", "trunk"],
    primaryMuscles: ["trunk", "quads"],
    secondaryMuscles: ["glutes"],
    equipmentAlternatives: [[]],
    exerciseClass: "trunk",
    purposes: ["general_function"],
    specificity: 0,
    fatigue: 1,
    alternatives: [],
  }),
  exercise({
    id: "controlled_mobility_sequence",
    name: "Controlled mobility sequence",
    patterns: ["squat", "hinge", "vertical_push"],
    primaryMuscles: [],
    secondaryMuscles: [],
    equipmentAlternatives: [[]],
    exerciseClass: "trunk",
    purposes: ["general_function"],
    specificity: 0,
    fatigue: 1,
    alternatives: [],
  }),
];

const BY_ID = new Map(EXERCISES.map((item) => [item.id, item]));

export function getExercise(id: string): ExerciseDefinition | undefined {
  return BY_ID.get(id);
}

export function equipmentSupports(
  exerciseDefinition: ExerciseDefinition,
  available: Equipment[],
): boolean {
  const set = new Set(available);
  return exerciseDefinition.equipmentAlternatives.some((alternative) =>
    alternative.every((item) => set.has(item)),
  );
}

export function isExerciseEligible(
  exerciseDefinition: ExerciseDefinition,
  input: QuestionnaireInput,
  equipment = input.facility.primaryEquipment,
): boolean {
  if (!equipmentSupports(exerciseDefinition, equipment)) return false;
  if (input.safety.excludedExercises.includes(exerciseDefinition.id))
    return false;
  if (
    exerciseDefinition.patterns.some((pattern) =>
      input.safety.excludedMovements.includes(pattern),
    )
  )
    return false;
  return true;
}

export interface ExerciseQuery {
  purpose: ExercisePurpose;
  patterns?: MovementPattern[];
  muscles?: Muscle[];
  preferredIds?: string[];
  maximumFatigue?: 1 | 2 | 3;
  requireLift?: "squat" | "bench" | "deadlift";
  requireCompetitionSpecificity?: boolean;
}

function scoreExercise(
  definition: ExerciseDefinition,
  query: ExerciseQuery,
): number {
  let score = definition.purposes.includes(query.purpose) ? 30 : -20;
  if (query.patterns?.some((pattern) => definition.patterns.includes(pattern)))
    score += 18;
  if (
    query.muscles?.some((muscle) => definition.primaryMuscles.includes(muscle))
  )
    score += 16;
  if (
    query.muscles?.some((muscle) =>
      definition.secondaryMuscles.includes(muscle),
    )
  )
    score += 4;
  if (query.preferredIds?.includes(definition.id)) score += 25;
  if (query.requireLift !== undefined && definition.lift === query.requireLift)
    score += 30;
  if (query.requireCompetitionSpecificity === true)
    score += definition.specificity * 15;
  if (
    query.maximumFatigue !== undefined &&
    definition.fatigue > query.maximumFatigue
  )
    score -= 20;
  score -= definition.fatigue;
  if (definition.partialSubstitute === true) score -= 5;
  return score;
}

export function rankExercises(
  input: QuestionnaireInput,
  query: ExerciseQuery,
  equipment = input.facility.primaryEquipment,
): ExerciseDefinition[] {
  return EXERCISES.filter((item) => isExerciseEligible(item, input, equipment))
    .filter(
      (item) =>
        query.maximumFatigue === undefined ||
        item.fatigue <= query.maximumFatigue,
    )
    .filter(
      (item) =>
        item.purposes.includes(query.purpose) ||
        query.purpose === "general_function",
    )
    .filter(
      (item) =>
        query.patterns === undefined ||
        query.patterns.some((pattern) => item.patterns.includes(pattern)),
    )
    .filter(
      (item) =>
        query.muscles === undefined ||
        query.muscles.some(
          (muscle) =>
            item.primaryMuscles.includes(muscle) ||
            item.secondaryMuscles.includes(muscle),
        ),
    )
    .filter(
      (item) =>
        query.requireLift === undefined || item.lift === query.requireLift,
    )
    .sort(
      (left, right) =>
        scoreExercise(right, query) - scoreExercise(left, query) ||
        left.id.localeCompare(right.id),
    );
}

export function choiceCandidates(
  ranked: ExerciseDefinition[],
): ChoiceCandidate[] {
  return ranked.slice(0, 5).map((item, index) => ({
    exerciseId: item.id,
    name: item.name,
    score: 100 - index * 10,
    tradeoff:
      item.partialSubstitute === true
        ? "Partial purpose match; use its own performance history."
        : `${item.exerciseClass.replace("_", " ")}; fatigue tier ${item.fatigue}; independent load progression.`,
  }));
}

export function musclesForPattern(pattern: MovementPattern): Muscle[] {
  const mapping: Record<MovementPattern, Muscle[]> = {
    squat: ["quads", "glutes"],
    hinge: ["hamstrings", "glutes"],
    horizontal_push: ["chest", "triceps"],
    vertical_push: ["front_delts", "triceps"],
    horizontal_pull: ["upper_back", "lats"],
    vertical_pull: ["lats", "biceps"],
    knee_flexion: ["hamstrings"],
    elbow_flexion: ["biceps"],
    elbow_extension: ["triceps"],
    lateral_raise: ["side_delts"],
    calf_raise: ["calves"],
    trunk: ["trunk"],
    carry: ["trunk"],
    locomotion: [],
  };
  return mapping[pattern];
}

/** True when a logged load means resistance added on top of bodyweight. */
export function usesAddedBodyweightLoad(exerciseId: string): boolean {
  return getExercise(exerciseId)?.loadType === "added_to_bodyweight";
}

/** Repairs a short label used by early saved powerlifting programs. */
export function displayExerciseName(exerciseId: string, name: string): string {
  return exerciseId === "competition_squat" && !/\bsquat\b/i.test(name)
    ? `${name} squat`
    : name;
}
